name: geneext
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - _r-mutex=1.0.1=anacondar_1
  - aiohttp=3.9.3=py310h2372a71_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - alignlib-lite=0.3=py310h99d9a7c_6
  - apsw=3.39.2.1=py310hba2f8c6_0
  - argcomplete=3.1.4=pyhd8ed1ab_0
  - argh=0.30.2=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - bcrypt=4.1.2=py310hcb5633a_0
  - bedtools=2.31.0=hf5e1c6e_3
  - binutils_impl_linux-64=2.40=hf600244_0
  - biopython=1.81=py310h2372a71_1
  - boto3=1.34.88=pyhd8ed1ab_0
  - botocore=1.34.88=pyge310_1234567_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bwidget=1.9.14=ha770c72_1
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.21.0=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cachetools=5.3.3=pyhd8ed1ab_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py310h2fee648_0
  - cgat-apps=0.7.2=py310h5aa3a86_1
  - cgatcore=0.6.16=pyhdfd78af_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - contourpy=1.2.1=py310hd41b1e2_0
  - coreutils=9.5=hd590300_0
  - cryptography=42.0.5=py310h75e40e8_0
  - curl=8.7.1=hca28451_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - drmaa=0.7.9=py_1000
  - expat=2.5.0=hcb278e6_1
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.51.0=py310h2372a71_0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - frozenlist=1.4.1=py310h2372a71_0
  - ftputil=5.1.0=pyhd8ed1ab_0
  - gcc_impl_linux-64=13.2.0=h338b0a0_2
  - gettext=0.21.1=h27087fc_0
  - gevent=23.9.0.post1=py310h216423f_1
  - gffutils=0.12=pyh7cba7a3_0
  - gfortran_impl_linux-64=13.2.0=h76e1118_2
  - google-api-core=2.18.0=pyhd8ed1ab_0
  - google-auth=2.29.0=pyhca7485f_0
  - google-cloud-core=2.4.1=pyhd8ed1ab_0
  - google-cloud-sdk=472.0.0=py310hff52083_0
  - google-cloud-storage=2.16.0=pyhca7485f_0
  - google-crc32c=1.1.2=py310hc5c09a0_5
  - google-resumable-media=2.7.0=pyhd8ed1ab_0
  - googleapis-common-protos=1.63.0=pyhd8ed1ab_0
  - graphite2=1.3.13=h58526e2_1001
  - greenlet=3.0.3=py310hc6cd4ac_0
  - grep=3.11=h3cbd922_0
  - grpcio=1.46.3=py310hba10ccf_0
  - gxx_impl_linux-64=13.2.0=h338b0a0_2
  - harfbuzz=8.2.1=h3d44ed6_0
  - htslib=1.20=h81da01d_0
  - icu=73.2=h59595ed_0
  - importlib-metadata=6.8.0=pyha770c72_0
  - jmespath=1.0.1=pyhd8ed1ab_0
  - joblib=1.4.0=pyhd8ed1ab_0
  - kernel-headers_linux-64=2.6.32=he073ed8_16
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - krb5=1.21.2=h659d440_0
  - lcms2=2.15=h7f713cb_2
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.1=cxx17_h59595ed_2
  - libblas=3.9.0=19_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=19_linux64_openblas
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcurl=8.7.1=hca28451_0
  - libdeflate=1.18=h0b41bf4_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-devel_linux-64=13.2.0=ha9c7c90_2
  - libgcc-ng=13.2.0=h807b86a_2
  - libgfortran-ng=13.2.0=h69a702a_2
  - libgfortran5=13.2.0=ha4646dd_2
  - libglib=2.78.0=hebfc3b9_0
  - libgomp=13.2.0=h807b86a_2
  - libiconv=1.17=h166bdaf_0
  - libjpeg-turbo=2.1.5.1=hd590300_1
  - liblapack=3.9.0=19_linux64_openblas
  - libnghttp2=1.58.0=h47da74e_0
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.24=pthreads_h413a1c8_0
  - libpng=1.6.39=h753d276_0
  - libprotobuf=4.25.3=h08a7969_0
  - libsanitizer=13.2.0=h7e041cc_2
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.44.0=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-devel_linux-64=13.2.0=ha9c7c90_2
  - libstdcxx-ng=13.2.0=h7e041cc_2
  - libtiff=4.6.0=h8b53f26_0
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.48.0=hd590300_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - macs2=2.2.9.1=py310h4b81fae_0
  - make=4.3=hd18ef5c_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - matplotlib-base=3.8.4=py310h62c0568_0
  - mdurl=0.1.0=pyhd8ed1ab_0
  - multidict=6.0.5=py310h2372a71_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-connector-c=6.1.11=h659d440_1008
  - ncurses=6.4=h59595ed_2
  - nomkl=1.0=h5ca1d4c_0
  - numpy=1.26.0=py310hb13e2d6_0
  - openjpeg=2.5.0=h488ebb8_3
  - openssl=3.2.1=hd590300_1
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.1.2=py310hcc13569_0
  - pango=1.50.14=ha41ecd1_2
  - paramiko=3.4.0=pyhd8ed1ab_0
  - pcre2=10.40=hc3806b6_0
  - pillow=10.0.1=py310h29da1c1_1
  - pip=23.3.1=pyhd8ed1ab_0
  - pixman=0.42.2=h59595ed_0
  - proto-plus=1.23.0=pyhd8ed1ab_0
  - protobuf=4.25.3=py310ha8c1f0e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyasn1=0.6.0=pyhd8ed1ab_0
  - pyasn1-modules=0.4.0=pyhd8ed1ab_0
  - pybigwig=0.3.22=py310h79000e5_2
  - pycparser=2.22=pyhd8ed1ab_0
  - pyfaidx=0.7.2.2=pyhdfd78af_0
  - pygments=2.16.1=pyhd8ed1ab_0
  - pynacl=1.5.0=py310h2372a71_3
  - pyopenssl=24.0.0=pyhd8ed1ab_0
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pysam=0.22.0=py310h41dec4a_0
  - pysftp=0.2.9=py_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.13=hd12c33a_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytz=2023.3.post1=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyvcf3=1.0.3=pyhdfd78af_0
  - pyyaml=6.0.1=py310h2372a71_1
  - quicksect=0.2.2=py310h4b81fae_8
  - r-base=4.3.1=h639d9d3_5
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - rich=13.6.0=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - ruffus=2.8.4=pyh864c0ab_1
  - s3transfer=0.10.1=pyhd8ed1ab_0
  - samtools=1.19.2=h50ea8bc_1
  - scikit-learn=1.4.2=py310h1fdf081_0
  - scipy=1.13.0=py310hb13e2d6_0
  - sed=4.8=he412f7d_0
  - setuptools=68.2.2=pyhd8ed1ab_0
  - simplejson=3.19.2=py310h2372a71_0
  - six=1.16.0=pyh6c4a22f_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_0
  - sqlalchemy=2.0.29=py310h2372a71_0
  - sqlite=3.44.0=h2c6b66d_0
  - sysroot_linux-64=2.12=he073ed8_16
  - threadpoolctl=3.4.0=pyhc1e730c_0
  - time=1.8=h516909a_0
  - tk=8.6.13=h2797004_0
  - tktable=2.10=h0c5db8f_5
  - typing-extensions=4.8.0=hd8ed1ab_0
  - typing_extensions=4.8.0=pyha770c72_0
  - tzdata=2023c=h71feb2d_0
  - ucsc-bedgraphtobigwig=455=h2a80c09_0
  - ucsc-wigtobigwig=447=h2a80c09_2
  - unicodedata2=15.1.0=py310h2372a71_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wheel=0.41.3=pyhd8ed1ab_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxt=1.3.0=hd590300_1
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py310h2372a71_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zope.event=5.0=pyhd8ed1ab_0
  - zope.interface=6.3=py310h2372a71_0
  - zstd=1.5.5=hfc55251_0
  - pip:
      - asgiref==3.7.2
      - cython==0.29.37
      - idna==3.6
      - importlib-resources==6.1.2
      - peaks2utr==1.2.5
      - pybedtools==0.9.1
      - tqdm==4.66.2
prefix: /home/grygoriyzolotarov/mambaforge/envs/geneext
